package oauth_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/xrl/suzuran-cloud/internal/oauth"
	"github.com/xrl/suzuran-cloud/internal/pkg/jwt"
)

func TestRandomString_UniqueAndURLSafe(t *testing.T) {
	a, err := oauth.RandomString(32)
	require.NoError(t, err)
	b, err := oauth.RandomString(32)
	require.NoError(t, err)
	assert.NotEqual(t, a, b)
	assert.NotEmpty(t, a)
	// base64url alphabet only
	for _, c := range a {
		assert.True(t, (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '-' || c == '_')
	}
}

func TestLoadConfig_Defaults(t *testing.T) {
	cfg := oauth.LoadConfig()
	require.NotNil(t, cfg)
	assert.Equal(t, "http://localhost:8888", cfg.Issuer)
	assert.Equal(t, "localhost", cfg.RPID)
	assert.Equal(t, "Suzuran Cloud", cfg.RPDisplayName)
	assert.Contains(t, cfg.RPOrigins, "http://localhost:5173")
	assert.Equal(t, 900, cfg.AccessTokenTTLSeconds)
	assert.Equal(t, 2592000, cfg.RefreshTokenTTLSeconds)
}

// TestJWT_RoundTripThroughOAuth verifies the RS256 key generated by jwt.SigningKey
// is the one used to verify tokens — i.e. the oauth and jwt packages share
// the same in-process key pair (no import cycle, both reference jwt.SigningKey).
func TestJWT_RoundTripThroughOAuth(t *testing.T) {
	token, err := jwt.GenerateToken(7, 3, "provider", []string{"org.read"}, "https://test", 900)
	require.NoError(t, err)

	claims, err := jwt.VerifyToken(token)
	require.NoError(t, err)
	assert.Equal(t, 7, claims.UserID)
	assert.Equal(t, 3, claims.OrgID)
	assert.Equal(t, "provider", claims.Role)
	assert.Equal(t, []string{"org.read"}, claims.Scopes)
	assert.Equal(t, "https://test", claims.Issuer)
}

func TestJWT_TamperedRejected(t *testing.T) {
	token, err := jwt.GenerateToken(1, 1, "user", nil, "https://test", 900)
	require.NoError(t, err)
	tampered := token[:len(token)-4] + "XXXX"
	_, err = jwt.VerifyToken(tampered)
	assert.Error(t, err)
}
